"""
File: Synthesize_Image.py
Description:
    Modular pipeline for Synthetic Star Image Generation.

    Structure:
    1. generate_raw_star_image(): Projects stars -> FITS file.
    2. apply_image_effects():     FITS -> NumPy Array (with optional noise).
    3. visualize_result():        NumPy Array + Quaternion -> Plot with Blue Circles.
    4. run_batch_from_csv():      Loads a CSV and runs the pipeline for multiple scenarios.
"""
import os
import csv
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits

# GIANT Imports
from giant.camera import Camera
from giant.camera_models import BrownModel
from giant.image import OpNavImage
from giant.stellar_opnav.stellar_class import StellarOpNav, StellarOpNavOptions
from giant.catalogs.gaia import Gaia
from giant.rotations import Rotation
import config

# --- CONFIGURATION ---
SAVE_DIR = os.path.join(config.DATA_DIR, 'generated')
if not os.path.exists(SAVE_DIR):
    os.makedirs(SAVE_DIR)

# =============================================================================
# PART 1: CREATE & SAVE (The Generator)
# =============================================================================
def generate_raw_star_image(target_quaternion, filename="synth_star_field.fits", base_flux=10000.0, psf_sigma=1.0):
    """
    Generates a star image from a quaternion and saves it as a FITS file.
    """
    print(f"--- Generating Raw FITS for Q={np.round(target_quaternion, 3)} ---")

    # A. Setup Camera (Zero distortion)
    model = BrownModel(
        kx=config.CAM_FOCAL_LENGTH, ky=config.CAM_FOCAL_LENGTH,
        px=config.CAM_CENTER_X, py=config.CAM_CENTER_Y,
        n_rows=config.IMG_RES, n_cols=config.IMG_RES
    )
    camera_obj = Camera(model=model, name='Synth_Cam')

    # B. Dummy File Trick (Required for GIANT memory init)
    temp_dummy = "temp_dummy_black.fits"
    if not os.path.exists(temp_dummy):
        fits.writeto(temp_dummy, np.zeros((config.IMG_RES, config.IMG_RES), dtype=np.uint8), overwrite=True)

    # C. Initialize GIANT
    opnav_image = OpNavImage(temp_dummy, observation_date=config.OBSERVATION_DATE)
    opnav_image.rotation_inertial_to_camera = Rotation(target_quaternion)

    # D. Run Identification (Math only)
    opts = StellarOpNavOptions()
    opts.star_id_options.catalog = Gaia()

    sopnav = StellarOpNav(camera_obj, options=opts)
    sopnav.add_images([opnav_image])

    # See dimmer stars
    sopnav.star_id.max_magnitude = config.MAX_MAGNITUDE

    sopnav.id_stars()

    # E. Extract Data & Rasterize
    projected_points = sopnav.queried_catalog_image_points[0]
    star_records = sopnav.queried_catalog_star_records[0]

    synth_image = np.zeros((config.IMG_RES, config.IMG_RES), dtype=np.float32)

    if projected_points is not None and star_records is not None and len(projected_points) > 0:
        xs = projected_points[0, :]
        ys = projected_points[1, :]
        mags = star_records['mag'].values

        print(f"   Rendering {len(xs)} stars...")

        for x, y, mag in zip(xs, ys, mags):
            if 0 <= x < config.IMG_RES and 0 <= y < config.IMG_RES:
                flux = base_flux * (10 ** (-0.4 * mag))

                # Draw Gaussian Spot
                rad = int(psf_sigma * 3)
                x_min, x_max = max(0, int(x)-rad), min(config.IMG_RES, int(x)+rad+1)
                y_min, y_max = max(0, int(y)-rad), min(config.IMG_RES, int(y)+rad+1)

                if x_max > x_min and y_max > y_min:
                    yy, xx = np.mgrid[y_min:y_max, x_min:x_max]
                    spot = flux * np.exp(-((xx - x)**2 + (yy - y)**2) / (2 * psf_sigma**2))
                    synth_image[y_min:y_max, x_min:x_max] += spot
    else:
        print("   No stars projected into FOV - saving blank image.")

    # G. Save FITS with Header
    save_path = os.path.join(SAVE_DIR, filename)
    hdu = fits.PrimaryHDU(synth_image)

    # Add metadata to the FITS header
    hdu.header['Q_X'] = target_quaternion[0]
    hdu.header['Q_Y'] = target_quaternion[1]
    hdu.header['Q_Z'] = target_quaternion[2]
    hdu.header['Q_W'] = target_quaternion[3]
    hdu.header['COMMENT'] = "Generated by GIANT Synthetic Pipeline"

    hdu.writeto(save_path, overwrite=True)
    print(f"   Saved FITS to: {save_path}")

    return save_path

# =============================================================================
# PART 2: POST-PROCESS (The Modifier)
# =============================================================================
def apply_image_effects(image_path, params=None):
    """
    Loads FITS, applies effects, returns NumPy array.
    """
    if params is None:
        params = {}

    print("--- Applying Image Effects ---")

    # Load FITS data
    with fits.open(image_path) as hdul:
        image = hdul[0].data.astype(np.float64)

    # Optional Effects
    if 'background' in params:
        # print(f"   Adding DC bias ({params['background']})")
        image += params['background']

    if 'noise' in params:
        # print(f"   Applying Gaussian noise (sigma={params['noise']})")
        noise = np.random.normal(0, params['noise'], image.shape)
        image += noise

    # Clip to positive
    image = np.clip(image, 0, None)

    # Scale to uint16 for better GIANT compatibility (simulate camera bit depth)
    max_val = np.max(image)
    if max_val > 0:
        image = (image / max_val * 65535).astype(np.uint16)
    else:
        image = image.astype(np.uint16)
    return image

# =============================================================================
# PART 3: VISUALIZE (The Viewer)
# =============================================================================
def visualize_result(image_data, quaternion):
    """
    Overlays 'Blue Circles' (Catalog Truth) on top of the image.
    """
    print("--- Visualizing Image (with noise) ---")

    # 1. Re-Calculate Star Positions from Quaternion
    model = BrownModel(
        kx=config.CAM_FOCAL_LENGTH, ky=config.CAM_FOCAL_LENGTH,
        px=config.CAM_CENTER_X, py=config.CAM_CENTER_Y,
        n_rows=config.IMG_RES, n_cols=config.IMG_RES
    )
    camera_obj = Camera(model=model, name='Vis_Cam')

    # Reuse dummy file for init
    temp_dummy = "temp_dummy_black.fits"
    if not os.path.exists(temp_dummy):
        fits.writeto(temp_dummy, np.zeros((config.IMG_RES, config.IMG_RES), dtype=np.uint8), overwrite=True)

    opnav_image = OpNavImage(temp_dummy, observation_date=config.OBSERVATION_DATE)
    opnav_image.rotation_inertial_to_camera = Rotation(quaternion)

    sopnav = StellarOpNav(camera_obj, options=StellarOpNavOptions())
    sopnav.star_id_options.catalog = Gaia()
    sopnav.add_images([opnav_image])
    sopnav.star_id.max_magnitude = config.MAX_MAGNITUDE
    sopnav.id_stars()

    cat_points = sopnav.queried_catalog_image_points[0]

    # 2. Plot
    plt.figure(figsize=(10, 10))
    ax = plt.gca()

    # A. The Image (Background)
    plt.imshow(np.log10(image_data.astype(float) + 1), cmap='gray', origin='upper')

    # B. The Blue Circles (Truth)
    if cat_points is not None:
        in_fov = (
            (cat_points[0, :] >= 0) & (cat_points[0, :] <= config.IMG_RES) &
            (cat_points[1, :] >= 0) & (cat_points[1, :] <= config.IMG_RES)
        )
        points = cat_points[:, in_fov]

        plt.scatter(points[0], points[1],
                    s=80, edgecolors='cyan', facecolors='none',
                    linewidth=1.5, label='Catalog Truth')
        print(f"   Projected {points.shape[1]} catalog stars onto visualization.")

    plt.title(f"Synthetic Result\nQ: {np.round(quaternion, 3)}")
    plt.xlabel("X [pix]")
    plt.ylabel("Y [pix]")
    plt.legend(loc='upper right')
    plt.tight_layout()
    plt.show()

# =============================================================================
# PART 4: BATCH PROCESSING (CSV Loader)
# =============================================================================
def run_batch_from_csv(csv_path, base_flux, psf_sigma, effects):
    """
    Reads a CSV file and generates an image for every row.
    """
    if not os.path.exists(csv_path):
        print(f"[ERROR] CSV file not found: {csv_path}")
        return

    print(f"\n=== Starting Batch Processing from: {csv_path} ===\n")

    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)

        count = 0
        for row in reader:
            filename = row['filename']
            try:
                q = [
                    float(row['qx']),
                    float(row['qy']),
                    float(row['qz']),
                    float(row['qw'])
                ]
            except ValueError as e:
                print(f"[SKIP] Invalid data in row for {filename}: {e}")
                continue

            print(f"Processing Scene {count+1}: {filename}")

            # 1. Generate Raw
            fits_path = generate_raw_star_image(q, filename=filename, base_flux=base_flux, psf_sigma=psf_sigma)

            # 2. Post Process
            final_image = apply_image_effects(fits_path, params=effects)

            # 3. Save Final (Overwrite raw with processed)
            # Read header from raw to preserve metadata
            with fits.open(fits_path) as hdul_raw:
                raw_header = hdul_raw[0].header

            hdu = fits.PrimaryHDU(final_image, header=raw_header)
            hdu.writeto(fits_path, overwrite=True)

            count += 1

    print(f"\n=== Batch Complete. Generated {count} images in {SAVE_DIR} ===")

# =============================================================================
# MAIN
# =============================================================================
if __name__ == "__main__":
    # --- GLOBAL SETTINGS ---
    BASE_FLUX = 20000.0
    PSF_SIGMA = 1.5
    EFFECTS = {'background': 20.0, 'noise': 1.0}

    # --- MODE SELECTION ---
    # Set this to True to run the batch from CSV, False to run single test
    RUN_BATCH_MODE = True

    CSV_FILENAME = "scenarios.csv"
    CSV_PATH = os.path.join(config.DATA_DIR, CSV_FILENAME)

    if RUN_BATCH_MODE:
        # Create a sample CSV if it doesn't exist (for demonstration)
        if not os.path.exists(CSV_PATH):
            print("CSV not found, please create 'scenarios.csv' or ensure it exists.")
        else:
            run_batch_from_csv(CSV_PATH, BASE_FLUX, PSF_SIGMA, EFFECTS)

    else:
        # Single Run Mode (Legacy)
        q_orion = [-0.704416026, 0.061628417, 0.0, 0.707106781]
        fits_path = generate_raw_star_image(q_orion, filename="Single_Scenario.fits", base_flux=BASE_FLUX, psf_sigma=PSF_SIGMA)
        final_image = apply_image_effects(fits_path, params=EFFECTS)
        hdu = fits.PrimaryHDU(final_image)
        hdu.writeto(fits_path, overwrite=True)
        visualize_result(final_image, q_orion)